export const REGISTER_USER_NAME = "REGISTER_USER_NAME";
export const USER_CONNECTED = "USER_CONNECTED";
export const SEND_MASSEGE = "SEND_MASSEGE";
export const SHOW_USERLIST = "SHOW_USERLIST";
export const USER_TYPING = "USER_TYPING";
export const USER_DISCONNECTED = "USER_DISCONNECTED";